version: "3"
services:
  luban-web:
    build: .
    image: luban-web
    container_name: "luban-web"
    depends_on:
      - redis
      - mysql
      - nginx 
    volumes:
      - .:/usr/local/src/luban-web
    network_mode: host
  
  redis:
    image: "redis"
    container_name: "redis"
    restart: always
    volumes:
      - ../data/redis:/data
    command: redis-server --requirepass "rst200233"
    network_mode: host

  mysql:
    image: "mysql:8.0"
    container_name: "mysql"
    restart: always
    volumes:
     - ../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rst200233
      MYSQL_DATABASE: luban  
    network_mode: host

  nginx:
    image: "nginx"
    restart: always
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/dist:/usr/local/src/luban-web/client/dist
    network_mode: host